project:
  type: website
  output-dir: docs

website:
  title: "richardvo-cs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme: vapor
    css: styles.css
    toc: true
    include-in-header: _includes/iconify.html


